# -*- coding: utf-8 -*-
"""23 july.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18r7qCJDFohHWcuHlY86Bj_QA6tY-XIup
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style ('darkgrid')

# independend
edu = np.array ([1,2,3,4,5])

# dependent
salary = np.array([200,300,400,500,600])

# we are going to train model that predict "salary" from "edu"

edu

salary

plt.scatter(edu,salary)
plt.xlabel('Independet ---> Edu')
plt.ylabel("Dependent ---> Salary")
plt.show()

import statsmodels.api as sm

x1 = sm.add_constant(edu)

x1

model = sm.OLS(salary,x1).fit()

model.summary ()

# edu ---- >4.5

100+100*4.5

model.predict([1.0,11])

y_hat = 100+100*edu

y_hat

plt.scatter(edu,salary)
plt.plot(edu,y_hat,color = "red")
plt.xlabel('Independet ---> Edu')
plt.ylabel("Dependent ---> Salary")
plt.show()

# in our case "salary" is y (actual value)

salary

x1

# predicted value
y_hat = model.predict(x1)

y_hat

from sklearn.metrics import mean_squared_error, mean_absolute_error

print ('mean squared error:'),mean_squared_error(salary , y_hat)

0.00000000000000000000000005169878828456423

print('mean absolute error: ',mean_absolute_error(salary,y_hat))



















